




!ERROR 1743085885.6477857

logs: Fail to get logs.

error raised: Traceback (most recent call last):
  File "T:\Python\BingGo\BingGo\main.py", line 24, in <module>
    b.run()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\app.py", line 955, in run
    self._run_prepare()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\app.py", line 925, in _run_prepare
    root = self.build()
           ^^^^^^^^^^^^
  File "T:\Python\BingGo\BingGo\display.py", line 722, in build
    self.war_screen = WarScreen(self.args)
                      ^^^^^^^^^^^^^^^^^^^^
  File "T:\Python\BingGo\BingGo\display.py", line 64, in __init__
    Clock.schedule_interval(self.debug, 0.1)  # 1表示尽可能频繁地调用
                            ^^^^^^^^^^
AttributeError: 'WarScreen' object has no attribute 'debug'





!ERROR 1743086357.8520482

logs: []

error raised: Traceback (most recent call last):
  File "T:\Python\BingGo\BingGo\main.py", line 24, in <module>
    b.run()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 379, in idle
    Clock.tick()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\clock.py", line 733, in tick
    self.post_idle(ts, self.idle())
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\clock.py", line 776, in post_idle
    self._process_events()
  File "kivy\\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "T:\Python\BingGo\BingGo\display.py", line 131, in debug
    print(self.war.ai.get_possible_moves(self.beach, 0))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "T:\Python\BingGo\BingGo\intelligence6.py", line 528, in get_possible_moves
    if i != None and i > 7:
                     ^^^^^
TypeError: '>' not supported between instances of 'Qizi' and 'int'





!ERROR 1743086401.5416727

logs: []

error raised: Traceback (most recent call last):
  File "T:\Python\BingGo\BingGo\main.py", line 24, in <module>
    b.run()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 379, in idle
    Clock.tick()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\clock.py", line 733, in tick
    self.post_idle(ts, self.idle())
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\clock.py", line 776, in post_idle
    self._process_events()
  File "kivy\\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "T:\Python\BingGo\BingGo\display.py", line 131, in debug
    print(self.war.ai.get_possible_moves(self.beach, 0))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "T:\Python\BingGo\BingGo\intelligence6.py", line 528, in get_possible_moves
    if i != None and i > 7:
                     ^^^^^
TypeError: '>' not supported between instances of 'Qizi' and 'int'





!ERROR 1743086536.2655852

logs: []

error raised: Traceback (most recent call last):
  File "T:\Python\BingGo\BingGo\main.py", line 24, in <module>
    b.run()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\app.py", line 956, in run
    runTouchApp()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
    EventLoop.mainloop()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 339, in mainloop
    self.idle()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\base.py", line 379, in idle
    Clock.tick()
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\clock.py", line 733, in tick
    self.post_idle(ts, self.idle())
  File "T:\Python\BingGo\BingGo\venv\Lib\site-packages\kivy\clock.py", line 776, in post_idle
    self._process_events()
  File "kivy\\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "T:\Python\BingGo\BingGo\display.py", line 142, in debug
    print(self.war.ai.get_possible_moves(self.beach, 0))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "T:\Python\BingGo\BingGo\intelligence6.py", line 528, in get_possible_moves
    if i != None and i > 7:
                     ^^^^^
TypeError: '>' not supported between instances of 'Qizi' and 'int'
